application: version-is
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# Static files
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /googlef432a4ac899fa943\.html
  static_files: static/googlef432a4ac899fa943.html
  upload: static/googlef432a4ac899fa943.html
- url: /assets/css
  static_dir: static/assets/css
- url: /assets/img
  static_dir: static/assets/img
- url: /assets/js
  static_dir: static/assets/js
# Administration tasks
- url: /tasks(.*)
  script: tasks.app
  login: admin
# Catch rest to API
- url: /.*
  script: main.app